<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.1</version>
		<relativePath/>
	</parent>
	<groupId>com.example</groupId>
	<artifactId>elasticache-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>elasticache-demo</name>
	<description>Demo project for Spring Boot with Elasticache</description>
	<properties>
		<java.version>17</java.version>
		<os.detected.classifier>osx-x86_64</os.detected.classifier>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.valkey.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-valkey</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>io.valkey</groupId>
			<artifactId>valkey-glide</artifactId>
			<!-- <classifier>${os.detected.classifier}</classifier> -->
			<classifier>osx-aarch_64</classifier>
			<version>2.3.0-rc2</version>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>imds</artifactId>
			<version>2.31.1</version>
		</dependency>
	</dependencies>

	<build>
		<extensions>
			<extension>
				<groupId>kr.motd.maven</groupId>
				<artifactId>os-maven-plugin</artifactId>
				<version>1.7.1</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
